### ISSUE TITLE
[bug] Identity balance doesn't update after epoch 

### ISSUE THREAD

**Issue by gades** [dashpay/dash-evo-tool#30]
<img width="298" alt="Screenshot 2024-10-31 at 08 38 58" src="https://github.com/user-attachments/assets/729a964f-506e-4ef2-9c06-47640cd4f93f">

My balance was not updated and for it I did recreate identity by restart app and remove identities.db

**Comment by qwizzie** [comment]
Should be fixed in v0.2.0 --> https://github.com/dashpay/dash-evo-tool/pull/14
New DET Binaries should be out any day now.

**Comment by gades** [comment]
@qwizzie I can't check - no binary files

**Comment by qwizzie** [comment]
@gades 'any day now' means in the next few days...

**Comment by qwizzie** [comment]
@gades https://github.com/dashpay/dash-evo-tool/releases/tag/v0.2.1  
binaries have been released.

**Comment by gades** [comment]
I'll check this issue after end of Epoch  (I saw button refresh)

**Comment by pauldelucia** [comment]
Is this resolved? @gades
