### ISSUE TITLE
refresh balance

### ISSUE THREAD

**Issue by sibTamias** [dashpay/dash-evo-tool#44]
I have installed DTM from dash-evo-tool-arm64-mac.zip a file on a macbook (M2 chip)
DTM works and, after withdrawing credits, it correctly reflects the remaining balance on each node. However, at the start of a new period, the accumulated credits from the previous period are not displayed! If you re-identify each node, then the current balance will be displayed correctly. How can this be done without having to re-identify? Or is this a bug and will it be fixed in the future?
In the screenshot, I can only see the balance after the withdrawal. No new credits have been added!
I want to see the "refresh" button )
![Screen1](https://github.com/user-attachments/assets/218638bd-bd7a-4e7d-8f83-4e7db82ca3ab)
I see there is a new instruction for installing DET.

**Comment by qwizzie** [comment]
This should be fixed in the next version. I think Paul added a refresh button for your existing Identities. Next DET version binaries should be out any day now.

**Comment by QuantumExplorer** [comment]
This should now be fixed.
