### ISSUE TITLE
Withdraw max button doesn't work correctly

### ISSUE THREAD

**Issue by gades** [dashpay/dash-evo-tool#55]
<img width="1041" alt="Screenshot 2024-11-14 at 11 43 34" src="https://github.com/user-attachments/assets/7de38e6c-59fa-4307-98ec-7189ba138f10">

My identity balance is 0.0611 DASH but when I push the max button I see wrong value 61.1467 instead of  0.0611 , Also the better to set Mac withdraw value

**Comment by QuantumExplorer** [comment]
This should be fixed in 0.3

**Comment by mm8191** [comment]
UQAZBBDZWQBTojSdN-Aw6Qe2FfudLWs5ZQmdf6JaRTeu-b9H

**Comment by mm8191** [comment]
ادرس ولت من هست دارایی ام گم شده ن بلدم چکارکنم و ن میکنم خودتان خاستین برگردونید
