### ISSUE TITLE
Two directories created in %APPDATA% in windows, consolidate into one

### ISSUE THREAD

**Issue by kxcd** [dashpay/dash-evo-tool#59]
In windows two directories are created.
![image](https://github.com/user-attachments/assets/ea897e54-eae1-46cd-bc94-233422233f59)
Please consolidate into `%AppData%\Roaming\Dash-Evo-Tool\` where the dir `data` and `config` can co-exist.

**Comment by pauldelucia** [comment]
I noticed this before on Mac as well but it should be resolved now. Would you like to confirm or can I close the issue?
