### ISSUE TITLE
why is 4 - used?

### ISSUE THREAD

**Issue by sibTamias** [dashpay/dash-evo-tool#82]
<img width="621" alt="Screenshot 2024-11-20 at 22 45 59" src="https://github.com/user-attachments/assets/dc4433a2-c20b-4819-b15c-c383b4fdfee6">

why is 4 - used , and 5 recommended ?
I created more than 10 IDs and selected from 1 to 7.

**Comment by pauldelucia** [comment]
It seems that only identity index 4 is being used in that wallet. We default to recommending new identities be the highest used identity index + 1.

Please double check in the Wallet screen Identity Creation tab that you have indexes 1-7.
