### ISSUE TITLE
feat: enable creating identity from current wallet balance

### ISSUE THREAD

**Issue by PastaPastaPasta** [dashpay/dash-evo-tool#87]
Funding options currently only show

<img width="305" alt="image" src="https://github.com/user-attachments/assets/1cb2cafa-a422-4fa1-ab24-a231ee9779f5">

However, this is a problem when a user already has Dash transferred into their DET wallet. There should be an ability to use existing UTXOs.

**Comment by pauldelucia** [comment]
Added this feature in v0.4
